export { default as SkeletonBlock } from './SkeletonBlock.vue'
export { default as SkeletonCard } from './SkeletonCard.vue'
export { default as SkeletonTable } from './SkeletonTable.vue'
export { default as SkeletonChart } from './SkeletonChart.vue'
export { default as SkeletonDashboard } from './SkeletonDashboard.vue'
export { default as FormSkeleton } from './FormSkeleton.vue'
export { default as ListSkeleton } from './ListSkeleton.vue'
export { default as PageHeaderSkeleton } from './PageHeaderSkeleton.vue'
